# My makefile
# put a tab character after the rule name, and before the command!

all:	
	g++ central_hub.cpp food_item.cpp warehouse.cpp transaction.cpp request.cpp -lboost_date_time

clean:
	rm -f a.out 
